webapp:
  extends:
    file: docker-compose-common-services.yml
    service: railsapp
  links:
    - db
    - redis
  env_file: .env.production
  environment:
    RACK_ENV: production
    RAILS_ENV: production
db:
  extends:
    file: docker-compose-common-services.yml
    service: mongodb
webserver:
  extends:
    file: docker-compose-common-services.yml
    service: nginx
  links:
    - webapp:webapp
redis:
  extends:
    file: docker-compose-common-services.yml
    service: redis
worker:
  extends:
    file: docker-compose-common-services.yml
    service: sidekiq
  env_file: .env
  environment:
    RAILS_ENV: production
  links:
    - db
    - redis
