webapp:
  extends:
    file: docker-compose-common-services.yml
    service: railsapp
  links:
    - db
  env_file: .env
  environment:
    RACK_ENV: production
    RAILS_ENV: production
    VIRTUAL_HOST: beer.docker
db:
  extends:
    file: docker-compose-common-services.yml
    service: mongodb
proxy:
  extends:
    file: docker-compose-common-services.yml
    service: nginx-proxy
