webapp:
  extends:
    file: docker-compose-common-services.yml
    service: railsapp
  links:
    - db
  environment:
    RACK_ENV: production
    RAILS_ENV: production
    SECRET_KEY_BASE: 560ea30c110b0ce9112b248441bde2e74d3d5120898894f1aef3202c63e9a3423f400cdd73dc58f7d71251fa0d991df3da671bba0f840521e3e48f55e299e11d
db:
  extends:
    file: docker-compose-common-services.yml
    service: mongodb
webserver:
  extends:
    file: docker-compose-common-services.yml
    service: nginx
  links:
    - webapp:webapp
