webapp:
  extends:
    file: docker-compose-common-services.yml
    service: railsapp
  links:
    - db
  env_file: .env
  environment:
    RACK_ENV: production
    RAILS_ENV: production
db:
  extends:
    file: docker-compose-common-services.yml
    service: mongodb
webserver:
  extends:
    file: docker-compose-common-services.yml
    service: nginx
  links:
    - webapp:webapp
