mongodb:
  image: mongo:3.0
  command: mongod --smallfiles --quiet
railsapp:
  build: .
  command: bundle exec unicorn -E production -c config/unicorn.rb
  volumes:
    - .:/myapp
nginx-proxy:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
redis:
  image: redis
sidekiq:
  build: .
  command: bundle exec sidekiq -e production -c 25
# Old nginx config
nginx:
  build: ./config/nginx
  ports:
    - "80:80"
